# -*- coding: utf-8 -*-
"""statistics1.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0PsE1HGMJ8_jI8IhGNUF8C6IpIjUwM7
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import statistics

#mean,median,mode
array=sns.load_dataset('tips')

array.head()

np.mean(array['total_bill'])

np.median(array['total_bill'])

statistics.mode(array['total_bill'])

sns.boxplot(array['total_bill'])

#plotting histogram , where kde=true means we are finding probability density with this
sns.histplot(array['total_bill'],kde=True)  # graph is little bit skewed towards the right

#iris dataset - flowers dataset
new = sns.load_dataset('iris')

new.head()





sns.histplot(new['sepal_width'],kde=True)
# folloing the gaussian distribution / normal distribution

sns.countplot(new['species'])
#bargraph/barchart

sns.countplot(array['total_bill'])

np.percentile(new['sepal_length'],[25,75])

np.percentile(new['sepal_width'],[30,98])

np.percent